version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      day: "tuesday"
      timezone: "America/New_York"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: direct
      - dependency-type: indirect
